### ISSUE TITLE
a question on running CSpider dataset

### ISSUE THREAD

**Issue by tyfann** [berlino/tensor2struct-public#10]
Hello, I want to run your code to reproduce the experiment on CSpider dataset and unfortunately I met up with a problem.
Here is how's that going: following your instruction in ReadMe file, I successfully updated and installed all packets metioned in setup script file. But when I tried to follow the Preprocessing step for CSpider training and enter "tensor2struct preprocess configs/spider/run_config/run_ch_spider_bert_baseline.jsonnet" on the command line, there is an error ocurring("KeyError: 'spider-bert'"), and the entire error info is :

Using default log base dir /data/data2/tyf/PycharmProject/tensor2struct-public
WARNING <class 'tensor2struct.models.enc_dec.EncDecPreproc'>: superfluous {'name': 'EncDecV2'}
Traceback (most recent call last):
  File "/data/data2/conda_envs/tensor2struct/bin/tensor2struct", line 33, in <module>
    sys.exit(load_entry_point('tensor2struct', 'console_scripts', 'tensor2struct')())
  File "/data/data2/tyf/PycharmProject/tensor2struct-public/tensor2struct/commands/run.py", line 241, in main
    preprocess.main(preprocess_config)
  File "/data/data2/tyf/PycharmProject/tensor2struct-public/tensor2struct/commands/preprocess.py", line 47, in main
    preprocessor = Preprocessor(config)
  File "/data/data2/tyf/PycharmProject/tensor2struct-public/tensor2struct/commands/preprocess.py", line 15, in __init__
    registry.lookup("model", config["model"]).Preproc, config["model"]
  File "/data/data2/tyf/PycharmProject/tensor2struct-public/tensor2struct/utils/registry.py", line 61, in instantiate
    return callable(**merged)
  File "/data/data2/tyf/PycharmProject/tensor2struct-public/tensor2struct/models/enc_dec.py", line 36, in __init__
    self.enc_preproc = registry.lookup("encoder", encoder["name"]).Preproc(
  File "/data/data2/tyf/PycharmProject/tensor2struct-public/tensor2struct/utils/registry.py", line 28, in lookup
    return _REGISTRY[kind][name]
KeyError: 'spider-bert'

I want to know how to solve it and thanks a lot for your reply!

**Comment by berlino** [comment]
It seems I forget to import certain modules properly. Sorry about this!

It should be fixed now.

**Comment by berlino** [comment]
Thanks for reporting this! Let me if it's fixed
