### ISSUE TITLE
A problem encountered while processing Spider data

### ISSUE THREAD

**Issue by unknowed-ER** [berlino/tensor2struct-public#6]
I have already finished "./setup" and download Spider, but found a problem:

```
(tensor2struct) fsx@FoolishCow:~/model/tensor2struct$ tensor2struct preprocess configs/spider/run_config/run_en_spider_bert_baseline.jsonnet
Traceback (most recent call last):
  File "/home/fsx/anaconda3/envs/tensor2struct/bin/tensor2struct", line 33, in <module>
    sys.exit(load_entry_point('tensor2struct', 'console_scripts', 'tensor2struct')())
  File "/home/fsx/anaconda3/envs/tensor2struct/bin/tensor2struct", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/fsx/anaconda3/envs/tensor2struct/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 954, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/fsx/anaconda3/envs/tensor2struct/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 542, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for tensor2struct
```

**Comment by berlino** [comment]
are you running tensor2struct on colab? This error seems to be a known problem, after a quick google search https://github.com/pytorch/fairseq/issues/2546

**Comment by unknowed-ER** [comment]
thanks for your help, but I didn't use colab  and [https://github.com/pytorch/fairseq/issues/2546](url) cannot fix it.

**Comment by berlino** [comment]
I guess it's probably a software version issue? As a reference, below are the versions that I'm using:

pip 20.2.3
Python 3.7.0

**Comment by unknowed-ER** [comment]
I'll try it ,thanks.
