### ISSUE TITLE
a question on running MLCG-codes

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [berlino/tensor2struct-public#7]
Hello, I want to run your code to reproduce the results for your paper"Meta Learning to Compositionally Generalize" and unfortunately I met up with a problem.
Here is how's that going: following your instruction in ReadMe file, I successfully updated and installed all packets metioned in setup script file.  But when I tried to follow the Preprocessing step for COGS training and enter "tensor2struct preprocess configs/cogs/run_config/run_cogs_comp.jsonnet" on the command line, there is an error ocurring("KeyError: 'cogs_enc'"), and the entire error info is :

Using default log base dir /data2/home/zhaoyi/SrcCode for MLCG
WARNING <class 'tensor2struct.models.enc_dec.EncDecPreproc'>: superfluous {'name': 'EncDec'}
Traceback (most recent call last):
  File "/data2/home/zhaoyi/anaconda3/envs/tensor2struct/bin/tensor2struct", line 33, in <module>
    sys.exit(load_entry_point('tensor2struct', 'console_scripts', 'tensor2struct')())
  File "/data2/home/zhaoyi/SrcCode for MLCG/tensor2struct/commands/run.py", line 241, in main
    preprocess.main(preprocess_config)
  File "/data2/home/zhaoyi/SrcCode for MLCG/tensor2struct/commands/preprocess.py", line 47, in main
    preprocessor = Preprocessor(config)
  File "/data2/home/zhaoyi/SrcCode for MLCG/tensor2struct/commands/preprocess.py", line 15, in __init__
    registry.lookup("model", config["model"]).Preproc, config["model"]
  File "/data2/home/zhaoyi/SrcCode for MLCG/tensor2struct/utils/registry.py", line 61, in instantiate
    return callable(**merged)
  File "/data2/home/zhaoyi/SrcCode for MLCG/tensor2struct/models/enc_dec.py", line 36, in __init__
    self.enc_preproc = registry.lookup("encoder", encoder["name"]).Preproc(
  File "/data2/home/zhaoyi/SrcCode for MLCG/tensor2struct/utils/registry.py", line 28, in lookup
    return _REGISTRY[kind][name]
KeyError: 'cogs_enc'

I want to know how to solve it and thanks a lot for your reply!

**Comment by berlino** [comment]
It should be fixed now!  Should come from the same issue as #10

**Comment by berlino** [comment]
Thanks for reporting this! Let me if it's fixed
